### ISSUE TITLE
Add first try of versus mode

### ISSUE THREAD

**Issue by Grabarz88** [Grabarz88/2048-Multiplayer#17]
Prototype of versus mode will be played against computer. On board 4x4, the players block and computers block will spawn. They willl take turns in making moves. 
Block behaviour:
- Blocks now have an owner. It will be symbolized by color of the block.
- When one player moves his blocks, they will act like in classic game. 
- After every move, a block with no owner ("neutral") will spawn.
-  When player's block hits enemy block, then:
                                                                        - If the enemy's block has higher value, player's block will stop moving on it
                                                                        - It the enemy's block has the same value, they will make fusion. Newly created block will 
                                                                           be owned by player
                                                                        - If the enemy's block has lower value, it will be pushed by player's block
- Player or enemy loses, when he will lost all of his blocks or he won't be able to make another move.

**Comment by potto99** [comment]
Added looong ago. Just changed the rules a little bit.
Currently working on 4 players' mode
